name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_LEGACY_PEER_DEPS: true  # Wymuszamy instalację zależności z konfliktami
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x  # Wersja kompatybilna z React 17
          
      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          npm install --legacy-peer-deps  # Naprawia problem z react-canvas-draw
          npm install ajv@8.12.0 ajv-keywords@5.1.0 --save-exact  # Wymusza poprawne wersje
        
      - name: Build frontend
        working-directory: frontend
        run: npm run build
        env:
          CI: false  # Ignoruje ostrzeżenia przy buildowaniu
          
      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"  # TO JEST KLUCZOWA ZMIANA!
          app_location: "frontend"
          api_location: "backend/api"
          output_location: "build"
