name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_LEGACY_PEER_DEPS: true
      REACT_APP_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      REACT_APP_SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          
      - name: Install dependencies
        working-directory: frontend
        run: |
          npm install --legacy-peer-deps
          npm install @supabase/supabase-js
        
      - name: Build frontend
        working-directory: frontend
        run: npm run build
        env:
          CI: false
          REACT_APP_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          REACT_APP_SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          
      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "frontend"
          api_location: "backend/api"
          output_location: "build"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
