name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_LEGACY_PEER_DEPS: true  # Naprawia problem z react-canvas-draw
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install --legacy-peer-deps
        
      - name: Build frontend
        working-directory: frontend
        run: npm run build
        env:
          CI: false
          
      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "frontend"     # Folder z kodem React
          output_location: "build"     # Folder build React (wewnątrz frontend/)
          api_location: "backend/api"  # Folder z Azure Functions
